"""empty message

Revision ID: b4444f857484
Revises: 8f59755a5e64
Create Date: 2020-08-12 23:21:25.970222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4444f857484'
down_revision = '8f59755a5e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    genre_names = ('Alternative', 'Blues', 'Classical', 'Country', 'Electronic',
        'Folk', 'Funk', 'Hip-Hop', 'Heavy Metal', 'Instrumental', 'Jazz',
        'Musical Theatre', 'Pop', 'Punk', 'R&B', 'Reggae', 'Rock n Roll',
        'Soul', 'Other')

    for name in genre_names:
        statement = """insert into "Genre" (name) values ('{}')  """.format(name)
        op.execute(statement)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    # ### end Alembic commands ###
